// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrxgkkpzhahuxnvbqpfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyeGdra3B6aGFodXhudmJxcGZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMDAzMzEsImV4cCI6MjA2OTU3NjMzMX0.BS2bRAUvkJdwovhL09E3kPN1veyN3qPnw2hgTa53Sco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});